import type { Metadata } from "next";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { PiBookBookmarkFill, PiStudentBold } from "react-icons/pi";
import { FaUsers } from "react-icons/fa";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<>
    <html lang="en">
      <body>
        <div
          className="sidebar"
          data-image="/light-bootstrap-dashboard-react/static/media/sidebar-3.9992d0ce.jpg"
          data-color="black"
        >
          <div
            className="sidebar-background"
            style={{
              backgroundImage:
                'url("/light-bootstrap-dashboard-react/static/media/sidebar-3.9992d0ce.jpg")',
            }}
          />
          <div className="sidebar-wrapper">
            <div className="logo d-flex align-items-center justify-content-start">
              <a
                href="https://www.creative-tim.com?ref=lbd-sidebar"
                className="simple-text logo-mini mx-1"
              >
                <div className="logo-img">
                  <PiBookBookmarkFill size={30} />
                </div>
              </a>
              <a
                className="simple-text"
                style={{ textDecoration: "none" }}
                href="http://www.creative-tim.com"
              >
                Colegio App
              </a>
            </div>
            <div className="nav">
              <li className="active">
                <a
                  aria-current="page"
                  className="nav-link active"
                  href="#/admin/dashboard"
                >
                  <FaUsers size={25} className="me-4" />
                  <p>Alta de usuarios</p>
                </a>
              </li>
              <li className="">
                <a className="nav-link" href="#/admin/user">
                  <PiStudentBold size={25} className="me-4" />
                  <p>Listado de alumnos</p>
                </a>
              </li>
            </div>
          </div>
        </div>
        <div className="main-panel" style={{ marginLeft: "260px" }}>
          <nav className="navbar navbar-expand-lg navbar-light bg-light">
            <div className="container-fluid d-flex justify-content-between">
              <h5>Panel de administración</h5>
              <button
                className="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation"
              >
                <span className="navbar-toggler-icon" />
              </button>
              <div className="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul className="navbar-nav">
                  <li className="nav-item">
                    <a className="nav-link active" aria-current="page" href="#">
                      Inicio
                    </a>
                  </li>
                  <li className="nav-item">
                    <a className="nav-link" href="#">
                      Log Out
                    </a>
                  </li>
                  </ul>
              </div>
            </div>
          </nav>
          {children}
        </div>
      </body>
    </html>
  </>
  );
}
